// <auto-generated />
namespace PTMS.HttpsAuthProxy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProxyPasscode2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProxyPasscode2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604041617591_ProxyPasscode2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
